### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by piegamesde** [jacktrip/jmess-jack#2]
Otherwise, this project is useless to us since we are not allowed to use it.

**Comment by dvzrv** [comment]
@jcacerec Are you the only contributor to this repository?
If so, please add a license and state this clearly, as otherwise noone is allowed to package this software (all rights reserved).

**Comment by jcacerec** [comment]
The source code had the license, but I just added a license file too.

**Comment by piegamesde** [comment]
Thank you
